watermark:
  position: [556, 1233, 701, 1267]
  ckpt_p: "./weights/sttn.pth"
  mask_expand: 30
  neighbor_stride: 10

enhance:
  RealESRGAN_model_path: "./weights/RealESRGAN_x2plus.pth"
  GFPGANer_model_path: "./weights/GFPGANv1.4.pth"